from datetime import datetime

REPORT_DATE = datetime.now().strftime("%Y%m%d")

HIGH_FORBIDDEN_THRESHOLD = 5

BRUTE_FORCE_LIMIT = 5
SCANNER_PATH_LIMIT = 5
DETECTION_WINDOW_SECONDS = 300
ENABLE_LEGACY_UNTIMED_DETECTION = True
PATH_TRAVERSAL_PATTERNS = ("../", "..\\")
PATH_TRAVERSAL_PATTERN = "../"
FAILED_LOGIN_STATUS_CODES = ("401", "403")
AUTHENTICATION_PATHS = (
    "/login",
    "/signin",
    "/auth/login",
    "/api/login",
    "/wp-login.php",
)

SCORE_401 = 2
SCORE_403 = 3
SCORE_FAILED_LOGIN = 5
SCORE_BRUTE_FORCE_BONUS = 10
SCORE_SCANNER = 4
SCORE_PATH_TRAVERSAL = 8

SEVERITY_LOW_MAX = 4
SEVERITY_MEDIUM_MAX = 9
SEVERITY_HIGH_MAX = 19

FAILED_LOGIN_LIMIT = 3
FORBIDDEN_LIMIT = 3
SUSPICIOUS_SCORE_LIMIT = 5

REPORTS_DIR = "reports"

HEADER_CHECK_TIMEOUT = 5

NVIDIA_BASE_URL = "https://integrate.api.nvidia.com/v1"
NVIDIA_MODEL_NAME = "meta/llama-3.1-8b-instruct"
NVIDIA_API_TIMEOUT_SECONDS = 30.0
NVIDIA_CONNECT_TIMEOUT_SECONDS = 5.0
NVIDIA_MAX_RETRIES = 0

AI_TEMPERATURE = 0.3
AI_TOP_P = 0.7
AI_TEST_MAX_TOKENS = 50
AI_EXPLAINER_MAX_TOKENS = 200

CHATBOT_MAX_TOKENS = 450
CHATBOT_MAX_QUESTION_LENGTH = 300
CHATBOT_TOP_INCIDENT_LIMIT = 5

DEFAULT_LOG_FILE = "logs/sample_access.log"
UPLOAD_DIRECTORY = "uploads"
UPLOAD_WORKSPACES_DIRECTORY = "workspaces"
UPLOAD_FILE_PREFIX = "current_"
ALLOWED_LOG_EXTENSIONS = (".log", ".txt")
MAX_UPLOAD_SIZE_BYTES = 2_097_152
MAX_UPLOAD_SIZE_LABEL = "2 MB"
UPLOAD_REQUEST_OVERHEAD_BYTES = 65_536
MAX_UPLOAD_REQUEST_BYTES = (
    MAX_UPLOAD_SIZE_BYTES + UPLOAD_REQUEST_OVERHEAD_BYTES
)

# Legacy constants are retained for backwards compatibility with older imports.
LOG_MIN_PART_COUNT = 4
LOG_STATUS_CODE_INDEX = 3

DASHBOARD_REFRESH_MILLISECONDS = 10_000

ANALYSIS_CACHE_MAX_ENTRIES = 64
ANALYSIS_CACHE_TTL_SECONDS = 300
ANALYSIS_CACHE_SCHEMA_VERSION = "2026-08-04-windowed-parser-v1"

CHAT_RATE_LIMIT = 30
CHAT_RATE_WINDOW_SECONDS = 60
UPLOAD_RATE_LIMIT = 6
UPLOAD_RATE_WINDOW_SECONDS = 300
LOGIN_RATE_LIMIT = 5
LOGIN_RATE_WINDOW_SECONDS = 300

SESSION_LIFETIME_HOURS = 8

VALID_MESSAGE_TYPES = (
    "success",
    "error",
    "info",
)

TARGET_URLS = [
    "https://github.com",
    "https://www.python.org",
]

SECURITY_HEADERS = [
    ("Content-Security-Policy", "Injection ve XSS Koruma Eksikligi"),
    ("Strict-Transport-Security", "Insecure Transport"),
    ("X-Content-Type-Options", "Security Misconfiguration"),
    ("X-Frame-Options", "Clickjacking Koruma Eksikligi"),
    ("Referrer-Policy", "Security Misconfiguration"),
]
